<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Drips | <?= @$title ?></title>
	<!-- jQuery -->
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<!-- Highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/github-gist.min.css"/>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('pre code').each(function (i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>
	<style type="text/css">
        <?= file_get_contents(__DIR__."/style.css"); ?>
	</style>
</head>
<body>
	<header id="page-header">
		<div class="header_img">
			<img src="data:image/png;base64,<?= @base64_encode(file_get_contents(__DIR__.'/../drips.png')); ?>" height="60" alt="Drips Logo"></img>
		</div>
		<h1><?= @$title ?></h1>
		<hr/>
	</header>
	<section id="content">
