<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Drips | <?= @$title ?></title>
	<style type="text/css">
        <?= file_get_contents(__DIR__."/style.css"); ?>
	</style>
</head>
<body>
	<header>
		<div class="header_img">
			<img src="data:image/png;base64,<?= @base64_encode(file_get_contents(__DIR__.'/../drips.png')); ?>" height="60" alt="Drips Logo"></img>
		</div>
		<h1><?= @$title ?></h1>
		<hr/>
	</header>
	<section id="content">
