<?php $title = "Datenbankverbindung fehlgeschlagen"; ?>
<?php include(__DIR__."/_header.phtml"); ?>
<h2>Verbindung zur Datenbank fehlgeschlagen.</h2>
<p>Drips kann keine Verbindung zu deiner Datenbank aufbauen. Du kannst deine Zugangsdaten in der Datei <code>dev.config.php</code>
im Ordner <code>config</code> überprüfen und ändern.</p>

<a href="./" class="button">Weiter</a>
<?php include(__DIR__."/_footer.phtml"); ?>
