<?php $title = "Rewrite-Modul aktivieren"; ?>
<?php include(__DIR__."/_header.phtml"); ?>
<h2>Offensichtlich ist das Rewrite-Modul deines Webservers nicht aktiviert.</h2>
<h3>Problemlösung</h3>
<p>Damit Drips mit schönen, benutzerdefinierten URLs arbeiten kann musst du das Rewrite-Modul deines Apache-Webservers installieren bzw. aktivieren.</p>
<pre><code>a2enmod rewrite</code></pre>
<cite>Solltest du kein Linux-System verwenden, sondern beispielsweise mit einem lokalen Webserver (wie z.B.: XAMPP) entwickeln,
musst du das Rewrite-Modul ebenso aktivieren. Dies kann über die jeweilige Konfigurationsdatei des Webservers festgelegt werden.</cite>
<a href="./" class="button">Weiter</a>
<?php include(__DIR__."/_footer.phtml"); ?>
