<?php $title = "Ungültige PHP-Version"; ?>
<?php include(__DIR__."/_header.phtml"); ?>
<p>Oh nein. Offensichtlich verwendest du eine veraltete oder nicht unterstützte PHP-Version.</p>
<p>Am besten aktualisierst du deine PHP-Version. Beachte, dass für die Ausführung von Drips mindestens PHP 5.5 erforderlich ist.</p>
<a href="./" class="button">Weiter</a>
<?php include(__DIR__."/_footer.phtml"); ?>
