<?php $title = "Ungültige PHP-Version"; ?>
<?php include(__DIR__."/_header.phtml"); ?>
<h2>Oh nein - offensichtlich verwendest du eine veraltete oder nicht unterstützte PHP-Version!</h2>
<p>Am besten aktualisierst du deine PHP-Version. Beachte, dass für die Ausführung von Drips <strong>mindestens PHP 5.5</strong> erforderlich ist.</p>
<a href="./" class="button">Weiter</a>
<?php include(__DIR__."/_footer.phtml"); ?>
